ARG BUILD_FROM
FROM ${BUILD_FROM}

ENV LANG C.UTF-8
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN \
    apt-get update \
    \
    && apt-get install -y --no-install-recommends \
        libasound2-data=1.1.3-5ubuntu0.5 \
        libasound2-dev=1.1.3-5ubuntu0.5 \
        libasound2-plugins=1.1.1-1ubuntu1 \
        libasound2=1.1.3-5ubuntu0.5 \
    \
	&& apt-get purge -y --auto-remove \
        libasound2-dev 
		
# Copy data for add-on
COPY run.sh /

RUN chmod a+x /run.sh
CMD [ "/run.sh" ]