ARG BUILD_FROM=hassioaddons/ubuntu-base:5.2.0
# hadolint ignore=DL3006
FROM ${BUILD_FROM}

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Setup base
# hadolint ignore=DL3003
RUN \
    apt-get update \
    \
    && apt-get install -y --no-install-recommends\
        build-essential=12.4ubuntu1 \
        cargo=0.42.0-0ubuntu1~18.04.1 \
        git=1:2.17.1-1ubuntu0.7 \
        libasound2-data=1.1.3-5ubuntu0.5 \
        libasound2-dev=1.1.3-5ubuntu0.5 \
        libasound2-plugins=1.1.1-1ubuntu1 \
        libasound2=1.1.3-5ubuntu0.5 \
        libssl-dev=1.1.1-1ubuntu2.1~18.04.5 \
        sox \
        sox libsox-fmt-all \
        jq \
        wget \
    \
    && apt-get purge -y --auto-remove \
        build-essential \
        cargo \
        git \
        libasound2-dev \
        libssl-dev \
    \
    && rm -fr \
        /tmp/* \
        /root/.cargo \
        /var/{cache,log}/* \
        /var/lib/apt/lists/*

# Copy data
COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]